name: 'CodeLogic Java Agent'
description: 'Scans Java artifacts into your '
inputs:
  version:
    description: 'The version of the agent docker image to use. Default is latest.'
    default: "latest"
    required: false
  codelogic_host:
    description: 'The host address of the CodeLogic instance without the "/codelogic/ui/" part.'
    required: true
  agent_uuid:
    description: 'The UUID of the Agent in CodeLogic.'
    required: true
  agent_password:
    description: 'The password for the agent.'
    required: true
  application_name:
    description: 'The Application node to create that will be the parent of all objects found in the scan.'
    required: true
  scan_space:
    description: 'The name of the scan space that the data will be saved to. 
    If specified, a ScanSpace with this name will be created if not found. 
    If not specified, information will be saved to the default ScanSpace.'
    required: false
  scan_path:
    description: 'A comma-separated list of files and folders to scan. Must start with /github/workspace/'
    default: "/github/workspace"
    required: false
  scan_path_depth:
    description: 'During scanning, this value will be used as the depth of subdirectories to traverse before stopping.'
    default: '1'
    required: false
  recursive_filter:
    description: 'A comma-separated list of substrings to key off of to trigger recursive analysis (jar within jar).'
    required: false
  method_filter:
    description: 'A comma-separated list of Java package prefixes that should be included in method-invokes-method relationships.'
    required: false
  database_identities:
    description: 'A comma-separated list of database identities to use in the creation of relationships.'
    required: false
  force_rescan:
    description: 'Forces jCape to rescan already scanned artifacts.'
    default: 'false'
    required: false
  expunge_scan_sessions:
    description: 'Instruct the server to delete all other scan sessions created by this agent and its configuration after the current scan session has completed successfully.'
    default: 'false'
    required: false
  java_opts:
    description: 'Java options to pass to the java command.'
    required: false

runs:
  using: 'docker'
  image: ${{ format('docker://public.ecr.aws/codelogic.com/codelogic_java:{0}', inputs.version) }}
  args: [
    "analyze",
    "-t scan",
    "-p ${{ inputs.scan_path }}",
    "-a ${{ inputs.application_name }}",
    "${{ inputs.scan_space != null && format('-s {0}', inputs.scan_space) || '' }}",
    "${{ inputs.recursive_filter != null && format('-r {0}', inputs.recursive_filter) || '' }}",
    "${{ inputs.method_filter != null && format('-m {0}', inputs.method_filter) || '' }}",
    "${{ inputs.database_identities != null && format('-d {0}', inputs.database_identities) || '' }}",
    "${{ inputs.force_rescan == 'true' && '--rescan' || '' }}",
    "${{ inputs.expunge_scan_sessions == 'true' && '-e' || '' }}"
  ]
  env:
    CODELOGIC_HOST: ${{ inputs.codelogic_host }}
    AGENT_UUID: ${{ inputs.agent_uuid }}
    AGENT_PASSWORD: ${{ inputs.agent_password }}
    SCAN_PATH_DEPTH: ${{ inputs.scan_path_depth }}
    JAVA_OPTS: ${{ inputs.java_opts }}

